# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-15 11:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginCredentials',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('pswd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('job_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('CO', 'Clinical Oficer'), ('Dr.', 'Doctor'), ('Nurse', 'Nurse')], default='', max_length=5)),
                ('facility', models.CharField(max_length=100)),
                ('level', models.IntegerField(null=True)),
                ('clinician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBioData',
            fields=[
                ('patient_no', models.IntegerField(primary_key=True, serialize=False)),
                ('id_no', models.CharField(max_length=10)),
                ('sir_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10)),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('NoK', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('physical_address', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50)),
                ('date_tested', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_levels',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('level', models.IntegerField(null=True)),
                ('p_id', models.CharField(max_length=25, null=True)),
                ('P_phone', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferInPatient',
            fields=[
                ('patient_no', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('sir_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10)),
                ('DOB', models.DateField()),
                ('incoming_date', models.DateField()),
                ('ccc_from', models.CharField(max_length=50)),
                ('date_confirmed', models.DateField()),
                ('date_enrolled', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='Transit_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_no', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('drug_refill', models.CharField(choices=[('Yes', 'Refilled'), ('No', 'Not Refilled')], default='Yes', max_length=5)),
                ('tests_done', models.TextField(max_length=500)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ARTVisitDetails',
            fields=[
                ('patient_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('visit_date', models.DateField()),
                ('drug_refill', models.CharField(choices=[('Yes', 'Refilled'), ('No', 'Not Refilled')], default='Yes', max_length=5)),
                ('tests_done', models.TextField(max_length=500)),
                ('comments', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('sir_name', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('first_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('relationship', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['sir_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalData',
            fields=[
                ('patient_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('date_confirmed', models.DateField()),
                ('date_enrolled', models.DateField()),
                ('used_arv', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default='No', max_length=5)),
                ('known_allergies', models.CharField(blank=True, max_length=500, null=True)),
                ('entry_point', models.CharField(max_length=30)),
                ('CD4_count', models.IntegerField(blank=True, null=True)),
                ('DLD', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
    ]
