# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginCredentials',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('pswd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicianData',
            fields=[
                ('job_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBioData',
            fields=[
                ('patient_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sir_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('id_no', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.IntegerField()),
                ('NoK', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('physical_address', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=50)),
                ('date_tested', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferInPatient',
            fields=[
                ('patient_no', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('sir_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('incoming_date', models.DateField()),
                ('ccc_from', models.CharField(max_length=50)),
                ('date_confirmed', models.DateField()),
                ('date_enrolled', models.DateField()),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='ARTVisitDetails',
            fields=[
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('visit_date', models.DateField()),
                ('drug_refill', models.CharField(choices=[('Yes', 'refilled'), ('No', 'Not refilled')], default='Yes', max_length=5)),
                ('tests_done', models.TextField(max_length=500)),
                ('comments', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='ClinicianLoginCredentials',
            fields=[
                ('job_id', models.IntegerField()),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.ClinicianData')),
                ('pswd', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('sir_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('relationship', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalData',
            fields=[
                ('patient_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData')),
                ('date_confirmed', models.DateField()),
                ('date_enrolled', models.DateField()),
                ('used_arv', models.CharField(max_length=20)),
                ('known_allergies', models.CharField(blank=True, max_length=500, null=True)),
                ('entry_point', models.CharField(max_length=30)),
                ('CD4_count', models.IntegerField(blank=True, null=True)),
                ('DLD', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['patient_no'],
            },
        ),
    ]
