# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicianlogincredentials',
            old_name='pswd',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='patientbiodata',
            name='id_no',
        ),
        migrations.AddField(
            model_name='cliniciandata',
            name='phone_no',
            field=models.IntegerField(default=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliniciandata',
            name='status',
            field=models.CharField(choices=[('CO', 'Clinical Oficer'), ('Dr.', 'Doctor'), ('Nurse', 'Nurse')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='patientbiodata',
            name='Sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='patientbiodata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 46, 33, 720772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbiodata',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientbiodata',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmedicaldata',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transferinpatient',
            name='Sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='transferinpatient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 16, 13, 47, 14, 405855, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferinpatient',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artvisitdetails',
            name='drug_refill',
            field=models.CharField(choices=[('Yes', 'Refilled'), ('No', 'Not Refilled')], default='Yes', max_length=5),
        ),
    ]
