# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=30)),
                ('date_tested', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clinician_login',
            options={'ordering': ['job_id']},
        ),
        migrations.AlterModelOptions(
            name='transfer_in',
            options={'ordering': ['incoming_date']},
        ),
        migrations.RenameField(
            model_name='clinician_details',
            old_name='job_number',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='clinician_details',
            old_name='first_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='clinician_login',
            old_name='job_number',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='clinician_login',
            old_name='last_login_time',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='transfer_in',
            old_name='facility_from',
            new_name='ccc_from',
        ),
        migrations.RenameField(
            model_name='transfer_in',
            old_name='date_coming',
            new_name='incoming_date',
        ),
        migrations.RenameField(
            model_name='visit_details',
            old_name='refilled',
            new_name='refill_info',
        ),
        migrations.RemoveField(
            model_name='clinician_details',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='clinician_login',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='clinician_login',
            name='sir_name',
        ),
        migrations.RemoveField(
            model_name='medical_data',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='transfer_in',
            name='date_started_ART',
        ),
        migrations.RemoveField(
            model_name='visit_details',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='visit_details',
            name='sir_name',
        ),
        migrations.AddField(
            model_name='next_of_kin',
            name='patient_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bio_data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bio_data',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='next_of_kin',
            name='sir_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='spouse',
            name='patient_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Bio_data'),
        ),
    ]
