# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171016_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinpatient',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientbiodata',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10),
        ),
    ]
