# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171016_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianLogin',
            fields=[
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.ClinicianData')),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
        migrations.RemoveField(
            model_name='clinicianlogincredentials',
            name='email_address',
        ),
        migrations.AlterModelOptions(
            name='nextofkin',
            options={'ordering': ['sir_name']},
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='patient_no',
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='sir_name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData'),
        ),
        migrations.DeleteModel(
            name='ClinicianLoginCredentials',
        ),
    ]
