# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-05 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171103_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transit_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_no', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=3)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='', max_length=10)),
                ('visit_date', models.DateTimeField(auto_now=True)),
                ('drug_refill', models.CharField(choices=[('Yes', 'Refilled'), ('No', 'Not Refilled')], default='Yes', max_length=5)),
                ('tests_done', models.TextField(max_length=500)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='artvisitdetails',
            name='patient_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData'),
        ),
        migrations.AlterField(
            model_name='clinicianlogin',
            name='job_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.ClinicianData'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='sir_name',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData'),
        ),
        migrations.AlterField(
            model_name='patientmedicaldata',
            name='patient_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.PatientBioData'),
        ),
    ]
