# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180105_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianlogin',
            name='user_name',
            field=models.CharField(default='uname', max_length=10),
            preserve_default=False,
        ),
    ]
