# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-06 10:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_clinicianlogin_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('CO', 'Clinical Oficer'), ('Dr.', 'Doctor'), ('Nurse', 'Nurse')], default='', max_length=5)),
                ('facility', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='imgs')),
                ('clinician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicianlogin',
            name='job_id',
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patientbiodata',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='ClinicianData',
        ),
        migrations.DeleteModel(
            name='ClinicianLogin',
        ),
    ]
