# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-07 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180206_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicianprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='email_address',
            field=models.EmailField(default='artborauser@art.health.go.ke', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicianprofile',
            name='clinician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicianprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
