# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180207_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_levels',
            fields=[
                ('session_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicianprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
