# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180213_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbiodata',
            name='id_no',
            field=models.CharField(default=3344556, max_length=10),
            preserve_default=False,
        ),
    ]
