# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_patientbiodata_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.IntegerField()),
            ],
        ),
    ]
