# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_levels',
            name='P_phone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='session_levels',
            name='p_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
