# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180214_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_levels',
            name='session_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
